apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: productpage
  namespace: argocd
spec:
  source:
    repoURL: https://github.com/aleksandrakojic/bookapp_devops.git
    path: manifests/kubernetes/productpage
  destination:
    server: https://kubernetes.default.svc
    namespace: staging
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true